### ISSUE TITLE
Fails to start in Android 10 / Q: TLS segment underaligned

### ISSUE THREAD

**Issue by callahad** [syncthing/syncthing-android#1291]
Hi, Syncthing does not launch in Android Q. The in-app logs report:

```
--------- beginning of main
--------- beginning of crash
03-13 23:12:51.467 W/SyncthingNativeCode(21438): error: "/data/app/com.nutomic.syncthingandroid-kgE8B7kQjgjrpd1_hr0zbw==/lib/arm64/libsyncthing.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
```

**Comment by callahad** [comment]
Looks like this is due to an upstream bug in Go: https://github.com/golang/go/issues/29674

**Comment by Catfriend1** [comment]
Hmmm I'll wait a little bit until q is really in it's final stage before looking deeper... Thanks for the report.

**Comment by kvaster** [comment]
I've monkey-patch-fix for now for me:
https://github.com/Catfriend1/syncthing-android/issues/370

**Comment by jaseemabid** [comment]
Same issue on the Pixel 2 official Q build. Cannot use syncthing anymore :/ 

```
--------- beginning of main
03-17 17:51:14.737 W/SyncthingNativeCode( 8900): error: "/data/app/com.nutomic.syncthingandroid-nNfpUCdCsSnNG2p4dSoerA==/lib/arm64/libsyncthing.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
--------- beginning of crash
03-17 17:52:00.946 W/SyncthingNativeCode( 8900): error: "/data/app/com.nutomic.syncthingandroid-nNfpUCdCsSnNG2p4dSoerA==/lib/arm64/libsyncthing.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
```

**Comment by CedricCabessa** [comment]
I confirm this patch https://github.com/Catfriend1/syncthing-android/commit/3a188d457c0a7add6b50c33bb78b640de195817f fixes the issue on my Pixel 2 on Android Q

https://github.com/Catfriend1/syncthing-android/issues/370

**Comment by danblah** [comment]
I confirm this patch https://github.com/Catfriend1/syncthing-android/commit/3a188d457c0a7add6b50c33bb78b640de195817f fixes the issue on my Pixel 3 XL on Android Q

https://github.com/Catfriend1/syncthing-android/issues/370

**Comment by CedricCabessa** [comment]
any news on this?

The bug is still present in the last version of syncthing and Q beta 4 (this is the final api)

I'm very happy with Catfriend's patch :-)

**Comment by imsodin** [comment]
Go 1.13 will have a proper fix. That's going to be released soon (beginning of August). And I personally wouldn't want to modify the Syncthing binary (or any binary) in general.

**Comment by hdurer** [comment]
This seems to still be an issue.

Is there a plan to create a new release soon that will pick up the go fix from last month?

**Comment by Catfriend1** [comment]
The plan is to build with go1.13 (containing the fix you've mentioned) as soon as it is released.
Currently, go 1.13rc2 is available, so it shouldn't take long until the final release.

**Comment by imsodin** [comment]
I plan to use go1.13 (RC or final release) for the next scheduled candidate release of syncthing-android next week.

**Comment by Catfriend1** [comment]
@imsodin I've tested go1.13rc2 and it works fine on the Q emulator.

**Comment by Athanasius** [comment]
Well, SyncThing is currently 100% non-functional on Android 10.  Any chance of a beta release using the go release candidate ?

**Comment by yacoob** [comment]
Yes, if possible please err on the side of conservative approach and don't keep Android version broken for long. Desktop version is relatively easy to recompile. Rolling your own apk is more difficult, plus sometimes impossible to install it due to device policies. :(

**Comment by Athanasius** [comment]
Indeed, building it for myself will be problematic given the golang-1.7 on Debian oldstable.  I'm more than willing to be a guinea pig if any dev has a version that should work on Android 10.

**Comment by AudriusButkevicius** [comment]
@imsodin we should re-release latest version built with new go perhaps.

**Comment by hdurer** [comment]
For simple users like myself stumbling upon this: syncthing-fork does work already.  Switching is a hassle but doable and gets your device back into working order in my experience.

**Comment by imsodin** [comment]
I will rerelease 1.2.2 as 1.2.2.1 with go1.13 soon (building now).

**Comment by duckpuppy** [comment]
I see the 1.2.2.1 release on the releases list here - has it been submitted to the Play Store?  I was just offered the 1.2.2 upgrade today, so I'm sure it'll be delayed for me a bit even if it's already been submitted.

**Comment by txoof** [comment]
What is the release schedule on the play store? Eagerly awaiting the update...

**Comment by Athanasius** [comment]
Indeed I'm still eagerly checking for an update a few times a day.

Sure, I could use syncthing-fork or any other special build with the fix, but it won't pick up the same settings, and with the official app in the state it's in I can't export my current settings.  That is another bug that needs addressing IMO.  Ensure the UI always has working menu to change/import/export settings no matter the state of network connections (this whole thing is a TLS issue brought on by a library issue, yes?).

Yes, I'll be exporting my settings the moment I get the official app update.

**Comment by Han9402** [comment]
1.2.2 in was Essential PH-1(Android 10) always loading and can't use.

**Comment by imsodin** [comment]
Since upgrading to go1.13 there's a problem with the build servers that I wasn't able to solve yet, that's why the announced release hasn't happened yet (and I can't currently give an ETA).

**Comment by Athanasius** [comment]
Thanks for giving us a heads up on the delay.

**Comment by yacoob** [comment]
I've just got an update to 1.2.2.2, with changelog mentioning go1.13 build and this issue. Sadly, syncthing crashes on startup now:

```
java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@664cd8f with Intent { cmp=com.nutomic.syncthing android/.service.SyncthingService }: java.lang.SecurityException: Permission Denial: startForeground from pid=29211, uid=10162 requires android.permission.FOREGROUND_SERVICE
```

I've sent the feedback via Android crash reporter, so you should have more details. I haven't denied any permissions to Syncthing, and I don't see a matching one to enable explicitly in app info.

**Comment by llzzrrdd** [comment]
Hi, same issue as yacoob described here (pixel 2).

**Comment by sungamagnus** [comment]
Same problem.
Looks like an easy fix by adding `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` to `AndroidManifest.xml` - https://stackoverflow.com/a/52382711

Created a simple PR https://github.com/syncthing/syncthing-android/pull/1400

**Comment by cciprian5** [comment]
After the update on the beta channel, the app is not opening anymore. It just crashes and there is no log written.

**Comment by sungamagnus** [comment]
My PR #1400 is 15 min too late (#1399)

**Comment by AudriusButkevicius** [comment]
Closing this as this issue is fixed. There is a separate issue which I am trying to fix on the mobile on a train, but github removed half the features from mobile ui, so not much fun.

**Comment by Athanasius** [comment]
I just got the 1.2.2.3 update and it appears to be working (sync'd a new file over from my server).  I've now made a backup of the settings in case of future hiccups....

**Comment by camachat** [comment]
1.2.2.3 works on Pixel 3

**Comment by achristianson** [comment]
Can confirm working. 1.2.2.3 Pixel 2.

**Comment by kopolee11** [comment]
I wanted to report that I am still having this problem even though I am using Syncthing version 1.2.2.3.4193 downloaded form the Aurora Store. I am using a Pixel 3 with GrapheneOS (https://github.com/grapheneos) 2019.09.18.14 preview.
