### ISSUE TITLE
Web interface not loading / cookie problem

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing-android#1995]
There is a cookie problem with syncthing. The solution is to delete the cookies. How do I do this on android in your app?

There is the same issue.

**Comment by imsodin** [comment]
Maybe removing the cache in the android app setting (not user data!) helps - worth a try.

**Comment by tomasz1986** [comment]
I think you may need to clear the cache of the WebView app, not Syncthing.

**Comment by tomasz1986** [comment]
> Clearing the cache doesn't solve the problem.

Of both the Syncthing app and the WebView app? If yes, then please try to clear data of just the WebView app (but not the Syncthing app, as doing so will reset all your Syncthing settings!).

**Comment by merlinuwe** [comment]
1. I made a backup of the Syncthing settings.
2. I deleted the cache _and_ the data.
3. I deinstalled syncthing.
4. I rebooted the smartphone.
5. I installed syncthing.
6. I loaded the backup file.

It solved the problem. ;-)

7. I'm happy. 😊

**Comment by kuanyui** [comment]
Don't sure if what I've encountered is same as this (web UI blink and refresh repeatedly today), also fixed via backup+uninstall+install+import backup.

https://github.com/syncthing/syncthing-android/assets/1370070/82ad2ae7-a241-41eb-b662-8714ea0a2fc6

**Comment by imsodin** [comment]
Anyone reading this, before taking the radical option maybe follow the suggested procedure first - so far no-one confirmed that they tried it and reported whether it helps:

> Of both the Syncthing app and the WebView app? If yes, then please try to clear data of just the WebView app (but not the Syncthing app, as doing so will reset all your Syncthing settings!).

**Comment by borozenetsvv** [comment]
I clean WebView app data. Not work.

**Comment by aquatix** [comment]
I cleared the cache of both Syncthing-Android and Android System WebView and it didn't resolve this issue for me.

Then I cleared storage of Android System WebView, but that also didn't help.

**Comment by michimussato** [comment]
Same issue here. After downgrade to 1.23.7 re-setup of all synced folders, Syncthing seems fine again. No clue about the cause though.

**Comment by bt90** [comment]
This has most likely the same root cause as https://github.com/syncthing/syncthing/issues/9208

**Comment by giorgiocaligiuri** [comment]
> 1. I made a backup of the Syncthing settings.
> 2. I deleted the cache _and_ the data.
> 3. I deinstalled syncthing.
> 4. I rebooted the smartphone.
> 5. I installed syncthing.
> 6. I loaded the backup file.
> 
> It solved the problem. ;-)
> 
> 7. I'm happy. 😊

It worked for me too, without steps 3, 4, 5

**Comment by borozenetsvv** [comment]
> It worked for me too, without steps 3, 4, 5

Confirmed. It worked for me too.

**Comment by imsodin** [comment]
Don't do this!  
It may "work", but it also removes the entire database. At best that's wasteful (everything needs rescanning), at worst it messes with your data (conflicts, resurrected deleted data, ...).

A fix in Syncthing is in the works.

**Comment by imsodin** [comment]
This hopefully is fixed by the latest RC. Reports from anyone that's currently affected and does the upgrade would be appreciated.

**Comment by michimussato** [comment]
> 1. I made a backup of the Syncthing settings.
> 
>     2. I deleted the cache _and_ the data.
> 
>     3. I deinstalled syncthing.
> 
>     4. I rebooted the smartphone.
> 
>     5. I installed syncthing.
> 
>     6. I loaded the backup file.
> 
> 
> It solved the problem. ;-)
> 
>     7. I'm happy. 😊

Successful here too! Thanks!

**Comment by imsodin** [comment]
Just got the update, and apparantly I was also effected before by this bug, and it works fine again since the latest RC upgrade.

@opusforlife2 As for F-Droid: There's no beta track there. Afaik you could create one by duplicating the app config at F-Droid, naming it something like "syncthing-android-rc".  
I won't release the syncthing RC as a real release, as that would force enable usage reporting.

**Comment by imsodin** [comment]
> @imsodin That's not what I'm referring to. When there is an emergency, the F-Droid maintainers can manually add a release instead of relying on the bot. It would be worth contacting them to see if that can be done here.

I don't want that to be done here, as it would release an RC and thus force enable usage reporting for everyone.

Anyway Jakob created a hot-fix tag on syncthing, I should get around to releasing that by end of day.

**Comment by wbadart** [comment]
> Don't do this! It may "work", but it also removes the entire database. At best that's wasteful (everything needs rehashing), at worst it messes with your data (conflicts, resurrected deleted data, ...).
> 
> A fix in Syncthing is in the works.

@imsodin I'm experiencing the issue and _haven't_ done this workaround. If you let us know when the patch lands on F-Droid, I can report back if that fixes it for me!

**Comment by tomasz1986** [comment]
> If you let us know when the patch lands on F-Droid, I can report back if that fixes it for me!

Synching project isn't responsible for F-Droid releases. They build and compile the app on their own, which is usually a few days after the official release here.
